FROM python:3.11-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de dépendances
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste de l'application
COPY . .

# Exposer le port de développement Django
EXPOSE 5125

# Lancer le serveur de développement
CMD ["python", "manage.py", "runserver", "0.0.0.0:5125"]
