# Generated by Django 4.2 on 2025-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='skill_images/')),
            ],
        ),
    ]
