# Generated by Django 5.2.4 on 2025-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='certification',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
