version: "3.9"

services:
  web:
    build:
      context: ./portfolio-api
    command: python manage.py runserver 0.0.0.0:5125
    environment:
      - DJANGO_ENV=prod
      - DJANGO_DEBUG=False
    volumes:
      - ./portfolio-api:/app
      - ./static:/app/static
    ports:
      - "5125:5125"
    env_file:
      - .env

  frontend:
    build:
      context: ./portfolio
    working_dir: /app
    command: npm run build
    volumes:
      - ./portfolio:/app
    depends_on:
      - web

  nginx:
    build:
      context: ./nginx
    
    depends_on:
      - web
      - frontend
