

services:
  web:
    build:
      context: ./portfolio-api
    command: python manage.py runserver 0.0.0.0:5125
    environment:
      - DJANGO_ENV=prod
      - DJANGO_DEBUG=False
    volumes:
      - ./portfolio-api:/app
      - ./static:/app/static
    ports:
      - "5125:5125"
    env_file:
      - .env

 


  
  frontend:
    build: ./portfolio
    ports:
      - "8081:80"
    volumes:
      - ./portfolio:/app
      - /app/node_modules
    

